# Exp 8 - Study of Tools in EDA

## Numpy Library
 Name - Ayush Pathare  
 PRN : 25070123166  
 Batch : EnTC A2

Why NumPy?
- Faster than lists
- Used for numerical computation
- Base for Pandas

In [3]:
#Declaration of NumPy

import numpy as np

a = np.array([10,20,30,40])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)


[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [6]:
#Dimension of Array

print(a.ndim)
print(b.ndim)

1
2


In [7]:
#Shape of Array

print(a.shape)
print(b.shape)

(4,)
(2, 3)


In [10]:
#Datatype

print(a.dtype)
print(b.dtype)

int64
int64


In [14]:
#In-built functions using numpy

#Initialise zeroes matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#Initialise ones matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#Initialise identity matrix

np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#Initialise Array Range

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
#Initialise Linespacing
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
c = a * 2
d = a + 5
print(c)
print(d)


[20 40 60 80]
[15 25 35 45]


In [22]:
a + 5

array([15, 25, 35, 45])

In [27]:
#Average, Median
print(np.mean(a))
print(np.median(a))

25.0
25.0


In [28]:
# Max and Min value
print("Maximum Value from 'a' array: ",np.max(a))
print("Minimum Value from 'a' array: ",np.min(a))

Maximum Value from 'a' array:  40
Minimum Value from 'a' array:  10


In [30]:
#Sum Function
np.sum(a)

np.int64(100)